### ISSUE TITLE
Make searchbar onclick wider

### ISSUE THREAD

**Issue by jabinx92** [jabinx92/react-messenger-redux#1]
Currently the searchbar onclick function on the chat application is a little narrow(there is little room to click on it. 

Make the searchbar onclick wider.

![Capture](https://user-images.githubusercontent.com/52295380/113195775-86e52780-9217-11eb-957a-fe8453dada60.JPG)

**Comment by priyalHedau15** [comment]
I would like to work on this issue,can u assign this to me

**Comment by jabinx92** [comment]
Hi Priya! sure you can work on the issue, I am going to assign it to you. Thanks!

**Comment by priyalHedau15** [comment]
@jabinx92 hey , I won't be able to work on this issue . Apologies 🙏

**Comment by Rishabhraghwendra18** [comment]
Hi @jabinx92 . May I work on this issue ? 😃

**Comment by rijusougata13** [comment]
@jabinx92  assign me please

**Comment by rijusougata13** [comment]
![7JUyMt1qfy](https://user-images.githubusercontent.com/52108435/113491844-504a2e00-94f1-11eb-9087-7e747aba6ea5.gif)

width increased
